GET http://localhost:5050/products HTTP/1.1

###

POST http://localhost:5050/product HTTP/1.1
content-type: application/json

{
    "name": "Product 3",
    "description": "Lorem impsum dolor est",
    "image_url": "https://m.media-amazon.com/images/I/91rQ3XfEYzL._SL1500_.jpg",
    "price": 19,
    "category": 1000,
    "brand": 2000,
    "rating": 6.7,
    "reviews": 12,
    "stock": 2,
    "sale": 0,
    "createdBy": 10000,
    "createdDate": "2023-03-01"
}

###

DELETE http://localhost:5050/product?id=4017 HTTP/1.1

### 

GET http://localhost:5050/users HTTP/1.1


###

GET http://localhost:5050/employees?limit=5 HTTP/1.1

### 

GET http://localhost:5050/info HTTP/1.1