POST http://localhost:5050/unprotected HTTP/1.1

 {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYWRjMmI5YTY1ZjA5YWQwNjQ1NmZjIiwiZW1haWwiOiJ0dWdhQG1haWwuY29tIiwiaWF0IjoxNjc5NDkyMjA4LCJleHAiOjE2Nzk0OTk0MDh9.uP8aQC1QxLvYDxMazmW5ollk4U25DU_gyF0l7BfiFE0"
 }

###

POST http://localhost:5050/protected HTTP/1.1

 {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYWRjMmI5YTY1ZjA5YWQwNjQ1NmZjIiwiZW1haWwiOiJ0dWdhQG1haWwuY29tIiwiaWF0IjoxNjc5NDkyMjA4LCJleHAiOjE2Nzk0OTk0MDh9.uP8aQC1QxLvYDxMazmW5ollk4U25DU_gyF0l7BfiFE0"
 }

###